### ISSUE TITLE
提示连接不到服务是什么原因啊？

### ISSUE THREAD

**Issue by baileikyo** [wangshenglia/gpt-3.5-turbo#1]
提示连接不到服务是什么原因啊？
调试提示的截图
![image](https://user-images.githubusercontent.com/60054225/222628432-4c8e54d2-2511-43fe-a6fd-e5b6c4696a0e.png)

**Comment by wangshenglia** [comment]
```
openai.api_key="Your api_key"
```
首先需要在这里填写你的openapi的key，我在关闭系统代理后复现出了你的这种情况，所以需要设置以下代理，在代码中添加以下语句：
``` Python
import os
os.environ["http_proxy"] = "http://127.0.0.1:10809"
os.environ["https_proxy"] = "http://127.0.0.1:10809"  #端口改为你自己的代理工具的端口，v2rayN为10809
```
我设置完代理后是可以正常连接了。

**Comment by baileikyo** [comment]
> 

感谢大佬，解决了
